name: Deploy game on Linux

on:
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repsoitory
        uses: actions/checkout@v4

      - name: Install G++ Multilib & 32 bit OpenGL library
        run: |
          sudo dpkg --add-architecture i386
          sudo add-apt-repository ppa:ubuntu-toolchain-r/test
          sudo apt update
          sudo apt install -y g++-11-multilib libgcc-s1:i386 libstdc++6:i386 libatomic1:i386 libgl1-mesa-dev:i386

      - uses: lukka/get-cmake@latest
      
      - name: Configure CMake
        run: > 
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
          -DCMAKE_TOOLCHAIN_FILE=${{github.workspace}}/cmake/LinuxToolchain.cmake --fresh

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j3

      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          name: linux-x86
          path: |
           bin/*.so
