name: Deploy game on Windows

on:
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repsoitory
        uses: actions/checkout@v4

      - uses: lukka/get-cmake@latest

      - name: Configure CMake
        run: > 
          cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

      - name: Build
        run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j3

      - name: Upload Binaries
        uses: actions/upload-artifact@v4
        with:
          name: win32
          path: |
            bin/*.dll